### PR TITLE
Add CONFIG to both ext.conf file

### PR DESCRIPTION
**Pull request by YusufAliSiddiqui**
Solves the problem of not being able to install eventmachine.

As seen here, https://github.com/eventmachine/eventmachine/issues/186

### CODE REVIEW

**Comment by sodabrew** [comment]
Thank you, I'll review this.
(Please remove the extra ~ swap files however!)

**Comment by YusufAliSiddiqui** [comment]
My bad. Removed the swap files.

**Comment by sodabrew** [comment]
Ok, I see - so this is not a correct fix in general because g++ is not the only compiler, and if there was a prior value for CONFIG["CXX"] we should not overwrite that. Ruby is supposed to, and does, provide CONFIG["CXX"] for us.

The workaround seemed to be needed only for the specific user who had a strange misconfiguration.

Are you seeing this problem yourself now?

**Comment by YusufAliSiddiqui** [comment]
Alright. 

I did have a similar problem myself, and the solution worked for me as well. Perhaps I had the same misconfiguration. 

That's why I thought it might be an apt change.

**Comment by sodabrew** [comment]
Interesting! What OS and Ruby version are you running on? If you run `irb` what do you see for `RbConfig::CONFIG["CXX"]`, for example, on my OS X machine, I get:

```
$ irb
irb(main):003:0> RbConfig::CONFIG["CC"]
=> "xcrun clang"
irb(main):004:0> RbConfig::CONFIG["CXX"]
=> "xcrun clang++"
```

**Comment by YusufAliSiddiqui** [comment]
Hmm. When I run the commands I get gcc and g++ respectively. 
I'm using Ubuntu 14.04 and ruby 2.2.1

**Comment by sodabrew** [comment]
This suggests you do not need any workaround. What error appears when you install the eventmachine gem?

**Comment by YusufAliSiddiqui** [comment]
Actually, the gem installs fine. When I run bundle install on the this gem file, http://pastie.org/10491556

I get the following error. http://pastie.org/10491553

**Comment by sodabrew** [comment]
You will need eventmachine 1.0.4 or higher to compile with Ruby 2.2.x, you've got 1.0.3 which isn't updated for the Ruby API changes.

**Comment by YusufAliSiddiqui** [comment]
I do have 1.0.8, don't know why it keeps using 1.0.3. Any suggestions?

**Comment by sodabrew** [comment]
Is this inside of a project with a Gemfile?

**Comment by YusufAliSiddiqui** [comment]
Yes it is.

**Comment by sodabrew** [comment]
I meant if you have a Gemfile.lock, or if another dependency has a specific version of eventmachine in the Gemfile. (note that the typical use of a Gemfile excludes all other systemwide gems.)

**Comment by YusufAliSiddiqui** [comment]
Yeah, I do have a gemfile.lock .

Okay, so I think I figured it out. I changed the version of the eventmachine in the .lock file, and now it doesn't give that error. 

However, it's giving "An error occurred while installing pg (0.17.1), and Bundler cannot continue." this now.

**Comment by YusufAliSiddiqui** [comment]
Turns out, I had to install postgresQL too. It works now. Thanks!

**Pull request closed without merging**
