### PR TITLE
Eventmachine LE

### PR DESCRIPTION
**Pull request by sodabrew**
This PR will track a merge of ibc/eventmachine-le into mainline eventmachine.

A brief history: around EM 0.12.x, EM was lacking solid IPv6 support, so @cabo and @ibc began working on this in a fork. EM was heading towards its 1.0 release, and the fork was doing some experimental work at the time, so they kept separate gems.

Today: eventmachine 1.0.x is stable and in common use across the Ruby world. eventmachine-le 1.1.x is stable and used by a smaller group with IPv6 needs.

What's next: eventmachine will skip the 1.1.x version numbers, eventmachine 1.2.0 will include the work from eventmachine-le. Goal date is March 2015.

### CODE REVIEW

**Comment by sodabrew** [comment]
Well the goal date came and went, and in the mean time I've done a few EM 1.0.x releases incorporating many bug fixes and cleanups. Once I've cleared through all the things I can get into 1.0.x, I'll resume work towards 1.2.0 here.

**Comment by brodock** [comment]
just want to say thanks for all the work here and coordination involved on getting both projects together again!

**Comment by sodabrew** [comment]
March 2016, eventmachine 1.2.0 is coming!

**Comment by ibc** [comment]
Great work!

**Comment by sodabrew** [comment]
EventMachine 1.2.0 is released! https://rubygems.org/gems/eventmachine/versions/1.2.0

**Pull request closed without merging**
