### PR TITLE
Fixes for Ruby 3, misc

### PR DESCRIPTION
**Pull request by MSP-Greg**
This has several commits.  Most importantly, it updates EM to work with Ruby 3, as changes to Process::Status were needed.

It also updates test_process.rb and various files for local use and testing.

On AppVeyor, it successfully builds a Windows gem for use with Ruby 2.2 thru 3.0, both 64 and 32 bit.

### CODE REVIEW

**Comment by rkoster** [comment]
While trying out these changes on ubuntu bionic we encountered the following compilation error:
```
gem install eventmachine-1.3.0.dev.1.gem
Building native extensions. This could take a while...
ERROR:  Error installing eventmachine-1.3.0.dev.1.gem:
        ERROR: Failed to build gem native extension.

    current directory: /root/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/eventmachine-1.3.0.dev.1/ext
/root/.rbenv/versions/3.0.1/bin/ruby -I /root/.rbenv/versions/3.0.1/lib/ruby/3.0.0 -r ./siteconf20210623-16492-gisv8b.rb extconf.rb
checking for openssl/ssl.h... yes
checking for openssl/err.h... yes
checking for BIO_read() in -lcrypto... yes
checking for SSL_CTX_new() in -lssl... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_thread_fd_select()... yes
checking for inotify_init() in sys/inotify.h... yes
checking for writev() in sys/uio.h... yes
checking for pipe2() in unistd.h... yes
checking for accept4() in sys/socket.h... yes
checking for SOCK_CLOEXEC in sys/socket.h... yes
checking for sys/event.h... no
checking for epoll_create1() in sys/epoll.h... yes
checking for clock_gettime()... yes
checking for CLOCK_MONOTONIC_RAW in time.h... yes
checking for CLOCK_MONOTONIC in time.h... yes
checking for TLS_server_method() in openssl/ssl.h... yes
checking for SSL_CTX_set_min_proto_version in openssl/ssl.h... yes
CXXFLAGS= -Wall -Wextra -Wno-deprecated-declarations -Wno-ignored-qualifiers -Wno-unused-result -Wno-address
creating Makefile

current directory: /root/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/eventmachine-1.3.0.dev.1/ext
make DESTDIR\= clean

current directory: /root/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/eventmachine-1.3.0.dev.1/ext
make DESTDIR\=
compiling binder.cpp
compiling cmain.cpp
compiling ed.cpp
compiling em.cpp
compiling kb.cpp
compiling page.cpp
compiling pipe.cpp
compiling rubymain.cpp
rubymain.cpp:103:1: sorry, unimplemented: non-trivial designated initializers not supported
 };
 ^
rubymain.cpp:103:1: sorry, unimplemented: non-trivial designated initializers not supported
rubymain.cpp:103:1: sorry, unimplemented: non-trivial designated initializers not supported
rubymain.cpp: In function 'void event_callback_wrapper(uintptr_t, int, const char*, long unsigned int)':
rubymain.cpp:247:87: warning: 'VALUE ruby::backward::cxxanyargs::rb_rescue(VALUE (*)(...), VALUE, VALUE (*)(...), VALUE)' is deprecated: Use of ANYARGS in this function is deprecated [-Wdeprecated-declarations]
   rb_rescue(VALUEFUNC(event_callback), (VALUE)&e, VALUEFUNC(event_error_handler), Qnil);
                                                                                       ^
In file included from /root/.rbenv/versions/3.0.1/include/ruby-3.0.0/ruby/internal/anyargs.h:83:0,
                 from /root/.rbenv/versions/3.0.1/include/ruby-3.0.0/ruby/ruby.h:24,
                 from /root/.rbenv/versions/3.0.1/include/ruby-3.0.0/ruby.h:38,
                 from em.h:24,
                 from project.h:168,
                 from rubymain.cpp:20:
/root/.rbenv/versions/3.0.1/include/ruby-3.0.0/ruby/backward/cxxanyargs.hpp:258:1: note: declared here
 rb_rescue(type *q, VALUE w, type *e, VALUE r)
 ^~~~~~~~~
Makefile:236: recipe for target 'rubymain.o' failed
make: *** [rubymain.o] Error 1

make failed, exit code 2
```

The above issue can be reproduced by building the following Dockerfile:
```Dockerfile
FROM ubuntu:bionic

RUN apt-get update && \
    apt-get install -y git curl libssl-dev libreadline-dev zlib1g-dev autoconf \
    bison build-essential libyaml-dev libreadline-dev libncurses5-dev libffi-dev libgdbm-dev

RUN curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
ENV PATH /root/.rbenv/shims:/root/.rbenv/bin:$PATH
RUN rbenv install 3.0.1 && rbenv global 3.0.1

RUN git clone https://github.com/MSP-Greg/eventmachine && \
    cd eventmachine && \
    git checkout 3-fixes && \
    gem build eventmachine.gemspec && \
    gem install eventmachine*.gem
```

**Comment by rkoster** [comment]
Did some additional by changing the base image:
- `FROM ubuntu:xenial` → fails with same error
- `FROM debian:buster` → works just fine

**Comment by MSP-Greg** [comment]
@rkoster Thanks for the info.  I'll add Ubuntu-18.04 to the CI and see about a fix...

**Comment by sodabrew** [comment]
Thanks for opening this @MSP-Greg, I'd like to land the Ruby 3 fixes and release it as EM 1.3

**Comment by MSP-Greg** [comment]
@sodabrew,

Good afternoon...

As @rkoster found, I added Ubuntu-18.04, and it's failing on some code (in this PR) only used with Ruby 3.0+.  Ubuntu-20.04, macOS 10.15, and Windows all pass, but Ubuntu-18.04 Ruby 3.0 & head/trunk both fail.

Any ideas?  I think it's a C/C++ issue, which I'm not that familiar with...

1. Pre-compiled Windows - it would be nice to provide.  If you don't want to enable AppVeyor (understandable), I can build it in my fork, and you could upload it?  I haven't had time to convert the code to GitHub Actions.

2. There are a few other PR's that look good, thoughts?  Don't know if you have time or have looked at them...

Hope things are well, Greg

**Comment by raggi** [comment]
LGTM overall, probably needs a rebase

**Comment by MSP-Greg** [comment]
@raggi

Thanks.  I can rebase, but in my last message and the message from @rkoster (and the current CI), there's problem compiling with Ubuntu 18.04, all other OS's are ok.  It's a C++/C thing,  which I'm not that familiar with.  Any ideas?

**Comment by MSP-Greg** [comment]
I just added a timeout to Actions jobs, as without a timeout, they'll run for 6 hours, as happened in CI with Ubuntu-18.04 Ruby 2.3.

**Comment by sodabrew** [comment]
I opened #949 to try a few things to see about this compiler error. The issue appears to be that earlier versions of g++ are strict about structure initialization order and missing members. There are a few fields left out of the process_data_type definition -- and I see even though you've copied this definition verbatim from process.c, Ruby uses a C compiler while EventMachine uses C++ and hits this strictness issue.

https://sonots.github.io/ruby-capi/de/de6/ruby_2ruby_8h_source.html#l01080

**Comment by sodabrew** [comment]
There is a function `rb_process_status_new` in process.c and while it is not static, it is also not made available via ruby headers to extensions. I tried adding `have_func('rb_process_status_new')` in extconf.rb, but it returns false :/

@ioquatix proposed exposing it in this PR: https://github.com/ruby/ruby/pull/4563

https://github.com/ruby/ruby/pull/4563/files#diff-9e49dc74fa060dcdff997b812e5f03ac53ba1aadebc0b40b26f00f881f135517R44

**Comment by sodabrew** [comment]
@MSP-Greg Check out https://github.com/eventmachine/eventmachine/pull/949/commits/88be06efc88f98f59a9efa632dd87aa7977c8713 what do you think?

**Comment by MSP-Greg** [comment]
Great & LGTM.  Thanks for your work on this.  What next?

**Comment by ioquatix** [comment]
For the sake of this work, and generally speaking, I don't believe we will change the `rb_process_status` struct layout.

**Comment by ioquatix** [comment]
Be careful with this, it's my fault it's not static.

The best check is

```
have_func('&rb_process_status_new')
```

otherwise you'll have weird results with some linkers.

See https://github.com/socketry/event/blob/d13999f32f29e0f971474811f01d8e38139aaf11/ext/event/extconf.rb#L36 for an example of the same problem (again my fault).

**Comment by MSP-Greg** [comment]
@ioquatix

Thanks for the tip.  Using either `have_func('&rb_process_status_new')` or `have_func('rb_process_status_new')` fails on Ubuntu and macOS.  The second works on Windows, the first does not.  I did look at https://github.com/socketry/event/pull/7 'https://github.com/socketry/event/pull/7' "Prefixing & should avoid checking for the symbol itself".

Somewhat confused, and I'm not that familiar with the difference.

**Comment by sodabrew** [comment]
@ioquatix - On MacOS:

```
checking for rb_process_status_new()... no
checking for &rb_process_status_new()... no
```

and putting in the definition and calling it in code:
```
+extern "C" {
+VALUE
+rb_process_status_new(rb_pid_t pid, int status, int error);
+}
+
 static VALUE t_get_subprocess_status (VALUE self UNUSED, VALUE signature)
 {
        VALUE proc_status = Qnil;
@@ -566,6 +571,8 @@ static VALUE t_get_subprocess_status (VALUE self UNUSED, VALUE signature)
 #ifdef IS_RUBY_3_OR_LATER
                        struct rb_process_status *data = NULL;

+                       VALUE process_status = rb_process_status_new(1, 2, 3);
```

results in this error:
```
dyld: Symbol not found: _rb_process_status_new
  Referenced from: /Users/astone/Code-sodabrew/eventmachine/lib/rubyeventmachine.bundle
  Expected in: flat namespace
```


The symbol IS found in libruby.bundle:
```
$ nm .rbenv/versions/3.0.1/lib/libruby.3.0.dylib | grep rb_process_status_new
000000000017e1a0 t _rb_process_status_new
```

But the lowercase letter designates this as a local (non-external) symbol.

**Pull request merged**
