### PR TITLE
Use clock_gettime and mach_absolute_time to make GetRealTime monotonic

### PR DESCRIPTION
**Pull request by sodabrew**
Based on clock_gettime from #496 with support for Mac OS X based on https://developer.apple.com/library/mac/qa/qa1398/_index.html

### CODE REVIEW

**Comment by rud** [comment]
Travis did not like the commit, is it common for the tests to hang?

**Comment by sodabrew** [comment]
Yes, I am working in #551 to resolve test problems.

**Comment by sodabrew** [comment]
Just found _the best_ article I've read on this topic: http://nadeausoftware.com/articles/2012/04/c_c_tip_how_measure_elapsed_real_time_benchmarking
I'm going to update this PR to use the same `#if defined(CLOCK_FOO)` pattern rather than `#if defined(OS_FOO)` pattern.

**Comment by sodabrew** [comment]
Turns out that RubyInstaller targets Windows XP as its baseline Win32 API, which is why I had to do the gymnastics for windows.h to give me GetTickCount64(), which means this wouldn't compile on XP. So I'll drop that for now with a note to use the newer function in the future. Another rebase is pending.

**Comment by sodabrew** [comment]
I have tested this on a few platforms now:
Linux (CLOCK_MONOTONIC_RAW)
FreeBSD 10 (CLOCK_MONOTONIC)
Mac OS X (mach_absolute_time)
Windows 8.1 (GetTickCount)

I'm in the middle of downloading a new Solaris 11 VM image.

**Comment by sodabrew** [comment]
Merged #551, rebased this, now we will get Travis unit tests.

**Pull request merged**
