### PR TITLE
Update buftok.rb

### PR DESCRIPTION
**Pull request by sferik**
I’ve replaced the version of `lib/em/buftok.rb` with the latest version from the [`buftok` gem](https://github.com/sferik/buftok/). I’m not sure how confident you are in your test suite, but it still passes after making this change.

Resolves https://github.com/eventmachine/eventmachine/issues/546.

### CODE REVIEW

**Comment by sodabrew** [comment]
Tests are in much improved shape. I took care of File.exist? in another PR. Please rebase to current master.

**Comment by sferik** [comment]
@sodabrew Done!

**Comment by sodabrew** [comment]
Looks like this will fix #338 and #342 as well.

**Comment by sferik** [comment]
@sodabrew Anything else holding up the merge? It would be :cool: if this change made it into the 1.0.5 release.

**Comment by sferik** [comment]
:boom:

**Pull request merged**
