### PR TITLE
Remove old ruby compat

### PR DESCRIPTION
**Pull request by sodabrew**

### CODE REVIEW

**Comment by sodabrew** [comment]
Possibly pull in `wait_for_single_fd` because rbx. https://github.com/brianmario/mysql2/commit/f1ee3fad48110e89b573d6cff2de21008aab2b5c

**Comment by DirtyF** [comment]
Hi,

Any reason to support end of EOL Rubies (2.2. and soon 2.3)?

**Comment by sodabrew** [comment]
Not dropping those. Isn’t worth the effort to sort out which features to assume available.

**Comment by DirtyF** [comment]
@sodabrew Rubocop helps target a minimum specific Ruby version.

**Comment by wyhaines** [comment]
On Thu, Jan 3, 2019 at 11:50 AM Frank Taillandier <notifications@github.com>
wrote:

> @sodabrew <https://github.com/sodabrew> Rubocop helps target a minimum
> specific Ruby version.
>

Rubocop can be helpful, but especially when dealing with 2.3, is there any
advantage to dropping support there that is currently worth the effort?


Kirk Haines

**Pull request merged**
