### PR TITLE
Jruby improve a bit

### PR DESCRIPTION
**Pull request by funny-falcon**
- add gather write
- add pause/resume
- add get_outbound_data_size

### CODE REVIEW

**Comment by sodabrew** [comment]
For improved JRuby PRs, would you be able to help me on #551 to get JRuby tests to pass as a baseline?

**Comment by sodabrew** [comment]
Could you rebase to current master (nearing a 1.0.5 release).

**Comment by funny-falcon** [comment]
i'll try

**Comment by funny-falcon** [comment]
ok, i've rebased

**Comment by sodabrew** [comment]
Thanks! Are these APIs that match up with existing APIs available in EM's C++ implementation? If not, I'd like to postpone until 1.2 for new APIs.

**Comment by funny-falcon** [comment]
Yes, it is couple of improvement and api which already exists in C++
implementation.

03.02.2015 5:27 пользователь "Aaron Stone" <notifications@github.com>
написал:
>
> Thanks! Are these APIs that match up with existing APIs available in EM's
C++ implementation? If not, I'd like to postpone until 1.2 for new APIs.

**Pull request merged**
